services:
  - type: web
    name: prototype-mdc-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: "postgres://user:password@host:port/dbname"
      - key: SECRET_KEY
        value: "ma_super_cle_secrete"
      - key: REDIS_URL
        value: "redis://..."
      - key: CORS_ORIGINS
        value: "https://mdc-manager.vercel.app"
